name: Recent Activity

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_TOKEN: ${{ secrets.RECENT_ACTIVITY_TOKEN }}
